# Generated by Django 4.2.20 on 2025-04-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("car_id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=50)),
                ("chassis", models.CharField(max_length=50)),
                ("engine_manufacturer", models.CharField(max_length=50)),
                (
                    "aerodynamics_package",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("horsepower", models.IntegerField(blank=True, null=True)),
                (
                    "tyre_supplier",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CAR",
            },
        ),
        migrations.CreateModel(
            name="Circuit",
            fields=[
                ("circuit_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("seating_capacity", models.IntegerField(blank=True, null=True)),
                ("number_of_drs", models.IntegerField(default=0)),
                ("drs_zones", models.IntegerField(default=0)),
                ("number_of_turns", models.IntegerField()),
                ("length_circuit", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "lap_record_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Street", "Street"),
                            ("Permanent", "Permanent"),
                            ("Temporary", "Temporary"),
                            ("Oval", "Oval"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CIRCUIT",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driver_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("nationality", models.CharField(max_length=50)),
                ("number_of_wins", models.IntegerField(default=0)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("pole_positions", models.IntegerField(default=0)),
                ("fastest_laps", models.IntegerField(default=0)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "DRIVER",
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("race_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "weather_condition",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("circuit_length", models.DecimalField(decimal_places=3, max_digits=8)),
                ("number_of_laps", models.IntegerField()),
                ("race_distance", models.DecimalField(decimal_places=3, max_digits=8)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.circuit"
                    ),
                ),
            ],
            options={
                "db_table": "RACE",
            },
        ),
        migrations.CreateModel(
            name="Records",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("Fastest_Lap_Time", "Fastest Lap Time"),
                            ("Most_Overtakes", "Most Overtakes"),
                            ("Most_Wins_Season", "Most Wins Season"),
                            ("Most_Poles_Season", "Most Poles Season"),
                            ("Championship_Record", "Championship Record"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fastest_lap_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "fastest_pit_stop",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("most_overtakes", models.IntegerField(blank=True, null=True)),
                ("record_description", models.CharField(max_length=255)),
                (
                    "driver_of_the_day",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dnf_count", models.IntegerField(blank=True, null=True)),
                (
                    "longest_dnf_laps",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "RECORDS",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("season_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("number_of_races", models.IntegerField()),
                (
                    "title_sponsor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "prize_money_awarded",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("time_gmt_class", models.DateTimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "champion_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="champion_seasons",
                        to="racing.driver",
                    ),
                ),
            ],
            options={
                "db_table": "SEASON",
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("sponsor_id", models.AutoField(primary_key=True, serialize=False)),
                ("sponsor_name", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=50)),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "annual_funding",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sponsorship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Title", "Title"),
                            ("Primary", "Primary"),
                            ("Secondary", "Secondary"),
                            ("Technical", "Technical"),
                            ("Official", "Official"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "SPONSOR",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contractor", "Contractor"),
                            ("Consultant", "Consultant"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "first_terms",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "STAFF",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=100)),
                ("team_country", models.CharField(max_length=50)),
                (
                    "team_principal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "tires_supplier",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("championships_won", models.IntegerField(default=0)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "TEAM",
            },
        ),
        migrations.CreateModel(
            name="Analyst",
            fields=[
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="racing.staff",
                    ),
                ),
                ("skill_specialty", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "ANALYST",
            },
        ),
        migrations.CreateModel(
            name="Engineer",
            fields=[
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="racing.staff",
                    ),
                ),
                (
                    "car_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("car_responsibility", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "ENGINEER",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="racing.staff",
                    ),
                ),
                (
                    "team_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("team_responsibility", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "MANAGER",
            },
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="racing.staff",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("experience_years", models.IntegerField()),
            ],
            options={
                "db_table": "MECHANIC",
            },
        ),
        migrations.CreateModel(
            name="Standings",
            fields=[
                ("standings_id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_id", models.IntegerField()),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("Team", "Team"), ("Driver", "Driver")], max_length=10
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("podiums", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("fastest_laps", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.season"
                    ),
                ),
            ],
            options={
                "db_table": "STANDINGS",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="racing.team"
            ),
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                ("contract_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("contract_start", models.DateTimeField()),
                ("contract_end", models.DateTimeField()),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.sponsor"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.team"
                    ),
                ),
            ],
            options={
                "db_table": "SPONSORSHIP",
            },
        ),
        migrations.AddField(
            model_name="season",
            name="champion_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="champion_seasons",
                to="racing.team",
            ),
        ),
        migrations.CreateModel(
            name="RaceResults",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("final_position", models.IntegerField(blank=True, null=True)),
                (
                    "points_scored",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("pit_stops", models.IntegerField(blank=True, null=True)),
                (
                    "fastest_lap_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("overtakes_made", models.IntegerField(blank=True, null=True)),
                ("laps_completed", models.IntegerField(blank=True, null=True)),
                (
                    "dnf_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Completed", "Completed"),
                            ("Mechanical", "Mechanical"),
                            ("Crash", "Crash"),
                            ("Disqualified", "Disqualified"),
                            ("Retired", "Retired"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.driver"
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.race"
                    ),
                ),
            ],
            options={
                "db_table": "RACE_RESULTS",
            },
        ),
        migrations.CreateModel(
            name="RaceEntry",
            fields=[
                ("entry_id", models.AutoField(primary_key=True, serialize=False)),
                ("grid_position", models.IntegerField(blank=True, null=True)),
                (
                    "upgrades_applied",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "race_modifications",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grid_position_final", models.IntegerField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.car"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.driver"
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="racing.race"
                    ),
                ),
            ],
            options={
                "db_table": "RACE_ENTRY",
            },
        ),
        migrations.AddField(
            model_name="race",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="racing.season"
            ),
        ),
        migrations.CreateModel(
            name="Penalties",
            fields=[
                ("penalty_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("Time", "Time"),
                            ("Grid", "Grid"),
                            ("Points", "Points"),
                            ("Disqualification", "Disqualification"),
                            ("Fine", "Fine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("time_penalty", models.IntegerField(blank=True, null=True)),
                ("penalty_reason", models.CharField(max_length=255)),
                (
                    "penalty_status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Appealed", "Appealed"),
                            ("Overturned", "Overturned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="racing.raceentry",
                    ),
                ),
            ],
            options={
                "db_table": "PENALTIES",
            },
        ),
        migrations.CreateModel(
            name="Failures",
            fields=[
                ("failure_id", models.AutoField(primary_key=True, serialize=False)),
                ("failure_type", models.CharField(max_length=50)),
                ("failure_description", models.CharField(max_length=255)),
                ("failure_lap", models.IntegerField(blank=True, null=True)),
                ("dnf", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="racing.raceentry",
                    ),
                ),
            ],
            options={
                "db_table": "FAILURES",
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="racing.team"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="racing.team"
            ),
        ),
    ]
